@startuml member-database

skinparam linetye ortho

entity "User" as user{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *name : text
    *phoneNumber : string <<loginId>>
    *password : string <<encrypted>>
    *shopId : string <<FK>>
}
entity "Shop" as shop{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *name : text
    *latitude : text
    *longitude : text
    *fullAddress : text
}
entity "User_Roles" as user_roles{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *userId : string <<FK>
    *roleId : string <<FK>
}

entity "Role" as role{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *name : string
}

shop ||--|{ user
user }|--|{ user_roles
role }|--|{ user_roles

@enduml