@startuml

skinparam linetye ortho

entity "User" as user{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *name : text
    *phoneNumber : text <<loginId>>
    *password : text <<encrypted>>
    *shopId : text <<FK>>
}
entity "Shop" as shop{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *name : text
    *latitude : text
    *longitude : text
    *fullAddress : text
}
entity "User_Roles" as user_roles{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *userId : text <<FK>
    *roleId : text <<FK>
}

entity "Role" as role{
    *id : UID <<generated>>
    *created : DateTime <<generated>>
    *modified : DateTime <<generated>>
    --
    *name : text
}

shop ||--|{ user
user }|--|{ user_roles
role }|--|{ user_roles

@enduml